services:
  - type: web
    name: review-insight-api
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
